# Generated by Django 4.2 on 2023-05-03 18:46

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(4, 'Zakończona'), (1, 'Czeka na przydzielenie'), (3, 'W toku'), (2, 'Przydzielona'), (5, 'Zarchiwizowana')])),
                ('category', models.SmallIntegerField(choices=[(3, 'Prawo administracyjne'), (5, 'Prawo rodzinne'), (2, 'Prawo cywilne'), (4, 'Prawo pracy'), (1, 'Prawo karne')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/uploads/%Y/%m/%d'), upload_to='')),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_akta.case')),
            ],
        ),
    ]
