# Generated by Django 4.2 on 2023-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0002_alter_case_category_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo cywilne', 'Prawo cywilne'), ('Prawo rodzinne', 'Prawo rodzinne'), ('Prawo karne', 'Prawo karne'), ('Prawo pracy', 'Prawo pracy'), ('Prawo administracyjne', 'Prawo administracyjne')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('W toku', 'W toku'), ('Zadekretowana', 'Zadekretowana'), ('Zarchiwizowana', 'Zarchiwizowana'), ('Czeka na dekretację', 'Czeka na dekretację'), ('Zakończona', 'Zakończona')]),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(max_length=32),
        ),
    ]
