# Generated by Django 4.2 on 2023-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0004_alter_case_category_alter_case_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='timestop',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='timestart',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo rodzinne', 'Prawo rodzinne'), ('Prawo pracy', 'Prawo pracy'), ('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo cywilne', 'Prawo cywilne'), ('Prawo karne', 'Prawo karne')], default='Prawo karne'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Zakończona', 'Zakończona'), ('W toku', 'W toku'), ('Zarchiwizowana', 'Zarchiwizowana')]),
        ),
    ]
