# Generated by Django 4.2 on 2023-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0004_alter_case_category_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo rodzinne', 'Prawo rodzinne'), ('Prawo karne', 'Prawo karne'), ('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo pracy', 'Prawo pracy'), ('Prawo cywilne', 'Prawo cywilne')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Czeka na dekretację', 'Czeka na dekretację'), ('Zadekretowana', 'Zadekretowana'), ('Zakończona', 'Zakończona'), ('Zarchiwizowana', 'Zarchiwizowana'), ('W toku', 'W toku')]),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=25, upload_to='documents/%Y/%m/%d'),
        ),
    ]
