# Generated by Django 4.2 on 2023-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0005_alter_case_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo karne', 'Prawo karne'), ('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo rodzinne', 'Prawo rodzinne'), ('Prawo cywilne', 'Prawo cywilne'), ('Prawo pracy', 'Prawo pracy')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='mail',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
