# Generated by Django 4.2 on 2023-05-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0008_alter_case_category_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo cywilne', 'Prawo cywilne'), ('Prawo pracy', 'Prawo pracy'), ('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo karne', 'Prawo karne'), ('Prawo rodzinne', 'Prawo rodzinne')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('W toku', 'W toku'), ('Zarchiwizowana', 'Zarchiwizowana'), ('Zakończona', 'Zakończona')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
