# Generated by Django 4.2 on 2023-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0009_alter_case_category_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo rodzinne', 'Prawo rodzinne'), ('Prawo cywilne', 'Prawo cywilne'), ('Prawo karne', 'Prawo karne'), ('Prawo pracy', 'Prawo pracy')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Zarchiwizowana', 'Zarchiwizowana'), ('Zadekretowana', 'Zadekretowana'), ('Zakończona', 'Zakończona'), ('W toku', 'W toku'), ('Czeka na dekretację', 'Czeka na dekretację')]),
        ),
    ]
