# Generated by Django 4.2 on 2023-05-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0011_alter_case_category_alter_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='number',
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo cywilne', 'Prawo cywilne'), ('Prawo karne', 'Prawo karne'), ('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo rodzinne', 'Prawo rodzinne'), ('Prawo pracy', 'Prawo pracy')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Zarchiwizowana', 'Zarchiwizowana'), ('Zakończona', 'Zakończona'), ('W toku', 'W toku')]),
        ),
    ]
