# Generated by Django 4.2 on 2023-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0012_remove_case_number_alter_case_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Zakończona', 'Zakończona'), ('Zarchiwizowana', 'Zarchiwizowana'), ('W toku', 'W toku')]),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cases', models.ManyToManyField(to='e_akta.case')),
            ],
        ),
    ]
