# Generated by Django 4.2 on 2023-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0014_alter_case_category_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo cywilne', 'Prawo cywilne'), ('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo pracy', 'Prawo pracy'), ('Prawo karne', 'Prawo karne'), ('Prawo rodzinne', 'Prawo rodzinne')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Zadekretowana', 'Zadekretowana'), ('Zakończona', 'Zakończona'), ('Czeka na dekretację', 'Czeka na dekretację'), ('W toku', 'W toku'), ('Zarchiwizowana', 'Zarchiwizowana')]),
        ),
    ]
