# Generated by Django 4.2 on 2023-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0018_alter_case_category_alter_case_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Zadekretowana', 'Zadekretowana'), ('Zakończona', 'Zakończona'), ('Zarchiwizowana', 'Zarchiwizowana'), ('Czeka na dekretację', 'Czeka na dekretację'), ('W toku', 'W toku')]),
        ),
    ]
