# Generated by Django 4.2 on 2023-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0019_rename_user_case_username_alter_case_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo pracy', 'Prawo pracy'), ('Prawo cywilne', 'Prawo cywilne'), ('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo karne', 'Prawo karne'), ('Prawo rodzinne', 'Prawo rodzinne')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Czeka na dekretację', 'Czeka na dekretację'), ('Zakończona', 'Zakończona'), ('Zadekretowana', 'Zadekretowana'), ('Zarchiwizowana', 'Zarchiwizowana'), ('W toku', 'W toku')]),
        ),
    ]
