# Generated by Django 4.2 on 2023-05-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0020_rename_username_case_user_alter_case_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo karne', 'Prawo karne'), ('Prawo rodzinne', 'Prawo rodzinne'), ('Prawo cywilne', 'Prawo cywilne'), ('Prawo pracy', 'Prawo pracy')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('W toku', 'W toku'), ('Zarchiwizowana', 'Zarchiwizowana'), ('Zakończona', 'Zakończona')]),
        ),
    ]
