# Generated by Django 4.2 on 2023-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_akta', '0022_alter_case_category_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Prawo cywilne', 'Prawo cywilne'), ('Prawo administracyjne', 'Prawo administracyjne'), ('Prawo rodzinne', 'Prawo rodzinne'), ('Prawo pracy', 'Prawo pracy'), ('Prawo karne', 'Prawo karne')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Zakończona', 'Zakończona'), ('W toku', 'W toku'), ('Zarchiwizowana', 'Zarchiwizowana')]),
        ),
    ]
